[package]
name                   = "myyazi"
description            = "Installer for myyazi, my fork of the Yazi terminal file manager"
version                = "26.9.1"
edition.workspace      = true
license.workspace      = true
authors.workspace      = true
homepage.workspace     = true
repository             = "https://github.com/ironyman/yazi"
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
yazi-macro = { path = "../yazi-macro", version = "26.9.1" }

# External dependencies
anyhow = { workspace = true }

[build-dependencies]
yazi-tty = { path = "../yazi-tty", version = "26.9.1" }

# External dependencies
anyhow = { workspace = true }

[[bin]]
name = "myyazi"
path = "src/main.rs"
