[fd.default]
kind = "view"
run  = "fd"

[rg.default]
kind = "view"
run  = "rg"

[trash."*"]
kind = "hub"
run  = "trash"

[pc.this]
kind = "scope"
run  = "pc"

[go.boot]
kind = "scope"
run  = "go"

[error.boot]
kind = "scope"
run  = "error"
